import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {CATALOG,itemSizes,canNest,canSupport,canLoad,canTurn,loadClass,layerPosition,packingPlan,nestingRise,packedVolume,packingMetrics,packUnit,recommend,canCompact,packedItem,movePack} from './engine.js';
import {ROOM_CATEGORIES,itemsForRoom} from './room-catalog.js';
import {block,label,itemModel,disposeGroup} from './models.js';
const $=id=>document.getElementById(id),escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let units=[],bag=[],category='bedroom',selected=null,recs=[],result=null,needsReview=false,revision=0;
let step=2,purpose='mixed',ready=false,calculating=false,modelVisible=false,thumbnailReady=false;
const thumbs={},reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const options=()=>({stack:$('stack').checked,access:$('access').checked,floor:$('floor').value});
let renderer,scene,camera,controls,modelRoot,animations=[],hoverTargets=[],fittedSpan=0,top=false,webgl=true;
let pendingPositions=null,manualResult=null,editMode=false,selectedPack=null,dragGhost=null;
function init3D(){try{renderer=new THREE.WebGLRenderer({canvas:$('scene'),antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.30;
 scene=new THREE.Scene();camera=new THREE.PerspectiveCamera(35,1,.1,100);scene.add(new THREE.HemisphereLight('#fff5ef','#70537d',2.7));const sun=new THREE.DirectionalLight('#fff4e8',4.0);sun.position.set(3,7,5);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-9,right:9,top:9,bottom:-9,near:.1,far:30});sun.shadow.normalBias=.025;scene.add(sun);const rim=new THREE.DirectionalLight('#c5a2ff',2);rim.position.set(-4,3,-3);scene.add(rim);
 modelRoot=new THREE.Group();scene.add(modelRoot);controls=new OrbitControls(camera,$('scene'));controls.enableDamping=true;controls.dampingFactor=.07;controls.maxPolarAngle=Math.PI*.48;controls.minPolarAngle=.03;controls.enablePan=false;controls.autoRotateSpeed=.9;controls.minDistance=2;controls.maxDistance=35;new ResizeObserver(resize).observe($('canvasWrap'));resize();
 renderer.setAnimationLoop(()=>{if(step!==4||!modelVisible||document.hidden)return;const time=performance.now();for(const a of animations){const p=Math.max(0,Math.min(1,(time-a.start)/650));a.g.position.y=a.base+Math.pow(1-p,3)*2.7;a.g.scale.setScalar(.96+.04*p);}controls.update();renderer.render(scene,camera);});
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();$('scene').addEventListener('pointermove',e=>{if(e.buttons)return;const r=$('scene').getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObjects(hoverTargets,true)[0];if(hit){let obj=hit.object;while(obj&&!obj.userData.item)obj=obj.parent;$('hoverLabel').hidden=!obj;if(obj)$('hoverLabel').textContent=obj.userData.item;}else $('hoverLabel').hidden=true;});$('scene').addEventListener('pointerleave',()=>$('hoverLabel').hidden=true);
 $('scene').addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','+','-'].includes(e.key)){e.preventDefault();if(e.key==='+')zoom(.85);else if(e.key==='-')zoom(1.15);else {const a=(e.key==='ArrowLeft'?-.15:.15);const p=camera.position.clone().sub(controls.target);p.applyAxisAngle(new THREE.Vector3(0,1,0),a);camera.position.copy(p.add(controls.target));controls.update();}}});
 }catch(e){webgl=false;$('modelFallback').hidden=false;$('status').textContent='3D could not start in this browser. You can still build your list and compare sizes.';}}
function resize(){if(!webgl||!renderer)return;const r=$('canvasWrap').getBoundingClientRect();if(!r.width||!r.height)return;renderer.setSize(r.width,r.height,false);camera.aspect=r.width/r.height;camera.updateProjectionMatrix();}
function positionCamera(unit,force=false){if(!webgl)return;const span=Math.max(unit.w,unit.d,2.4);if(force||Math.abs(span-fittedSpan)>.2){fittedSpan=span;controls.target.set(0,.35,0);camera.position.set(span*1.05,span*1.1,span*1.45);controls.minDistance=span*.7;controls.maxDistance=span*5;controls.update();top=false;$('topView').textContent='Top view';}}
function showModel(r,animate=true){if(!webgl||!renderer||!modelVisible||step!==4)return;disposeGroup(modelRoot);animations=[];hoverTargets=[];
 const u=r?.unit||{w:3,d:3,poly:[[0,0],[3,0],[3,3],[0,3]]};const origin=new THREE.Group();origin.position.set(-u.w/2,0,-u.d/2);modelRoot.add(origin);
 block(origin,-.13,-.22,-.13,u.w+.26,.15,u.d+.26,'#b59bd0');
 const shape=new THREE.Shape();u.poly.forEach((p,i)=>i?shape.lineTo(p[0],-p[1]):shape.moveTo(p[0],-p[1]));shape.closePath();const floorGeo=new THREE.ExtrudeGeometry(shape,{depth:.09,bevelEnabled:false});floorGeo.rotateX(-Math.PI/2);const floor=new THREE.Mesh(floorGeo,new THREE.MeshStandardMaterial({color:'#d6c7e9',roughness:.95}));floor.position.y=-.09;floor.receiveShadow=true;origin.add(floor);
 for(let j=0;j<u.poly.length;j++){const a=u.poly[j],b=u.poly[(j+1)%u.poly.length],dx=b[0]-a[0],dz=b[1]-a[1],len=Math.hypot(dx,dz);if(len<.01)continue;const back=Math.max(a[1],b[1])<.08||Math.max(a[0],b[0])<.08;const wall=new THREE.Mesh(new THREE.BoxGeometry(len,back?Math.min(1.08,u.height||2.4):.10,.045),new THREE.MeshStandardMaterial({color:back?'#9468bb':'#b494d0',roughness:.8}));wall.position.set((a[0]+b[0])/2,back?.54:.05,(a[1]+b[1])/2);wall.rotation.y=-Math.atan2(dz,dx);wall.castShadow=true;wall.receiveShadow=true;origin.add(wall);}
 // Reference marks stay on the base; the purple strip is explicitly a provisional front aisle.
 if($('access').checked&&r){const aisle=new THREE.Mesh(new THREE.PlaneGeometry(Math.max(.01,u.w-.07),.59),new THREE.MeshBasicMaterial({color:'#e9d986',transparent:true,opacity:.48,side:THREE.DoubleSide}));aisle.rotation.x=-Math.PI/2;aisle.position.set(u.w/2,.006,u.d-.30);origin.add(aisle);}
 const frontLabel=label(u.w.toFixed(2)+' m','#111111',1.3);frontLabel.position.set(u.w/2,-.12,u.d+.35);origin.add(frontLabel);const sideLabel=label(u.d.toFixed(2)+' m','#111111',1.3);sideLabel.position.set(u.w+.40,.1,u.d/2);origin.add(sideLabel);
 const logo=label('purplebox','#f4eafa',Math.min(u.w*.6,1.4));logo.position.set(u.w/2,.63,.015);origin.add(logo);
 if(r){let n=0;for(const p of r.placed){for(const layer of p.layers){const g=itemModel(layer),pos=layerPosition(p,layer),rot=pos.rot;
 g.position.set(pos.x,layer.y,rot?pos.z+layer.w:pos.z);if(rot)g.rotation.y=Math.PI/2;g.userData.packKey=p.packKey;g.userData.item=layer.name+(layer.tipped?' · turned on its side':'')+' · '+Math.round(layer.y*100)+' cm above floor';origin.add(g);hoverTargets.push(g);if(animate&&!reduced&&!editMode)animations.push({g,base:layer.y,start:performance.now()+Math.min(n,20)*65});n++;}}
 let index=0;for(const p of r.unplaced){for(const layer of p.layers){const g=itemModel(layer);const col=index%3,row=Math.floor(index/3);g.position.set(u.w+.4+col*1.0,0,row*1.0);g.scale.setScalar(.65);g.userData.packKey=p.packKey;g.userData.item=p.name+' · not placed in this unit';origin.add(g);hoverTargets.push(g);index++;}}}
 positionCamera(u);renderEditor();}
function zoom(factor){if(!webgl)return;camera.position.sub(controls.target).multiplyScalar(factor).add(controls.target);controls.update();}
function makeThumbnails(){if(thumbnailReady||!webgl)return;thumbnailReady=true;try{const r=new THREE.WebGLRenderer({alpha:true,antialias:true,preserveDrawingBuffer:true});r.setSize(240,180);r.setPixelRatio(1);r.outputColorSpace=THREE.SRGBColorSpace;r.toneMapping=THREE.ACESFilmicToneMapping;r.toneMappingExposure=1.45;const s=new THREE.Scene();s.add(new THREE.HemisphereLight('#fff7ef','#786384',3));const l=new THREE.DirectionalLight('#fff5ec',3);l.position.set(3,5,4);s.add(l);const cam=new THREE.PerspectiveCamera(32,4/3,.01,50);
 for(const i of CATALOG){const g=itemModel(i);g.position.set(-i.w/2,0,-i.d/2);s.add(g);const span=Math.max(i.w,i.d,i.h);cam.position.set(span*1.4,span*1.05,span*1.7);cam.lookAt(0,i.h*.43,0);r.render(s,cam);thumbs[i.id]=r.domElement.toDataURL('image/png');s.remove(g);disposeGroup(g);}r.dispose();r.forceContextLoss();}catch{}renderCatalog();renderBag();}
function thumbnail(i){return thumbs[i.id]?'<img src="'+thumbs[i.id]+'" alt="">':'<span class="thumb-fallback" aria-hidden="true">'+(i.emoji||'📦')+'</span>';}
const catalogueSizes=new Map();
function sizeOptions(i){const sizes=itemSizes(i),match=sizes.findIndex(p=>['w','d','h'].every(k=>Math.abs(p[k]-i[k])<.005));return (match<0?'<option value="" selected>Custom dimensions</option>':'')+sizes.map((p,n)=>'<option value="'+n+'" '+(n===match?'selected':'')+'>'+p.label+' · '+Math.round(p.w*100)+' × '+Math.round(p.d*100)+' × '+Math.round(p.h*100)+' cm</option>').join('');}
function renderCatalog(){const q=$('search').value.trim().toLowerCase(),room=ROOM_CATEGORIES.find(r=>r.id===category);const items=q?CATALOG.filter(i=>(i.name+' '+i.cat+' '+i.aliases.join(' ')).toLowerCase().includes(q)):itemsForRoom(CATALOG,category);$('roomDescription').textContent=room.description;$('catalogHeading').textContent=q?'Search results · all rooms':room.name;const chosen=bag.filter(b=>items.some(i=>i.id===b.id)).reduce((n,i)=>n+i.qty,0);$('catalogCount').textContent=items.length+' options'+(chosen?' · '+chosen+' selected':'');$('catalog').innerHTML=items.map(base=>{const selected=bag.find(b=>b.id===base.id),i=selected||{...base,...(catalogueSizes.get(base.id)||{})},n=selected?.qty||0;return '<article class="item-card '+(n?'is-selected':'')+'">'+thumbnail(base)+'<strong>'+escape(base.name)+'</strong><span class="selection-label">'+(n?'✓ Selected · '+n+' item'+(n>1?'s':''):'Not selected')+'</span><label class="catalog-size">Size<select data-catalog-size="'+base.id+'" aria-label="Size of '+escape(base.name)+'">'+sizeOptions(i)+'</select></label><div class="catalog-actions">'+(n?'<button data-minus="'+base.id+'" aria-label="Remove one '+escape(base.name)+'">−</button>':'')+'<button data-add="'+base.id+'">'+(n?'＋ Add another':'＋ Add item')+'</button></div></article>';}).join('')||'<p class="fineprint">No match. Add a custom item below.</p>';}
function renderBag(){const total=bag.reduce((n,i)=>n+i.qty,0);$('totalCount').textContent=total;$('volume').textContent=packedVolume(bag,$('stack').checked).toFixed(1)+' m³';$('bagNote').textContent=bag.length?'Dimensions are in centimetres. Beds include their mattress; do not add it twice.':'Your list is empty. Choose items to continue.';
 $('bagItems').innerHTML=bag.map(i=>'<article class="bag-item"><div class="bag-item-top">'+thumbnail(i)+'<div class="bag-item-info"><strong>'+escape(i.name)+'</strong><button class="remove-item" data-remove="'+i.id+'">Remove item</button></div></div><div class="item-adjustments"><div class="quantity"><button data-delta="-1" data-id="'+i.id+'" aria-label="Remove one '+escape(i.name)+'">−</button><span>'+i.qty+'</span><button data-delta="1" data-id="'+i.id+'" aria-label="Add one '+escape(i.name)+'">+</button></div><div class="edit-dims">'+(i.shape==='round'?[['w','Diameter'],['h','Height']]:[['w','Width'],['d','Depth'],['h','Height']]).map(([key,name])=>'<label>'+name+' (cm)<input type="number" min="5" max="600" step="1" value="'+Math.round(i[key]*100)+'" data-dim="'+key+'" data-id="'+i.id+'"></label>').join('')+'</div>'+packingControls(i)+'</div></article>').join('');}
function updatePackedReadout(t){const id=t.dataset.id||t.dataset.thickness,i=bag.find(i=>i.id===id),p=packedItem(i),el=t.closest('.bag-item').querySelector('.packed-readout');if(el)el.textContent=(i.kind==='bed'?'Includes mattress and dismantled frame. ':'Tabletop stored upright with removed legs. ')+'Packed: '+Math.round(p.w*100)+' × '+Math.round(p.d*100)+' × '+Math.round(p.h*100)+' cm. Confirm dismantling is possible.';}
function stackingControls(i){return (canNest(i)?'<div class="stack-setting"><label><input type="checkbox" data-nesting="'+i.id+'" '+(i.nesting?'checked':'')+'> These chairs are designed to nest together</label>'+(i.nesting?'<label>Height added by each extra chair (cm)<input type="number" min="5" max="'+Math.round(i.h*100)+'" value="'+Math.round(nestingRise(i)*100)+'" data-rise="'+i.id+'"></label><small>Measure one chair then two. Use the widest stack width and depth above.</small>':'<small>We can use the seat for smaller light items. Nesting chairs together is a separate option.</small>')+'</div>':'')+(canSupport(i)?'<div class="stack-setting"><label><input type="checkbox" data-support="'+i.id+'" '+(i.supportTop!==false?'checked':'')+'> Use '+(['chair','sofa'].includes(i.kind)?'the seat':(['shelf','rack'].includes(i.kind)?'the shelves':'this surface'))+' for light items</label><small>Estimate assumes a sturdy, protected surface. Switch off for delicate furniture or unsuitable luggage.</small></div>':'')+(canLoad(i)?'<div class="stack-setting"><label>Contents<select data-load="'+i.id+'">'+[['light','Light contents / clothing'],['heavy','Heavy contents'],['fragile','Fragile · keep separate']].map(([v,l])=>'<option value="'+v+'" '+(loadClass(i)===v?'selected':'')+'>'+l+'</option>').join('')+'</select></label>'+(canTurn(i)?'<label><input type="checkbox" data-turn="'+i.id+'" '+(i.allowTurn!==false?'checked':'')+'> Contents allow this box to turn onto another side</label>':'')+(i.id==='suitcase'?'<label>Packing position<select data-luggage="'+i.id+'"><option value="flat" '+(i.luggagePosition!=='upright'?'selected':'')+'>Lay flat · use space above</option><option value="upright" '+(i.luggagePosition==='upright'?'selected':'')+'>Keep upright</option></select></label>':'')+'</div>':'');}
function packingControls(i){const p=packedItem(i);return stackingControls(i)+'<div class="item-sizing"><label>Item size<select data-size="'+i.id+'">'+sizeOptions(i)+'</select></label>'+(canCompact(i)?'<label>Packing position<select data-packing="'+i.id+'"><option value="compact" '+(i.packing!=='assembled'?'selected':'')+'>Dismantled & upright</option><option value="assembled" '+(i.packing==='assembled'?'selected':'')+'>Keep assembled</option></select></label>':'')+'</div>'+(canCompact(i)&&i.packing!=='assembled'?'<label class="thickness">Packed bundle thickness (cm)<input type="number" min="8" max="200" value="'+Math.round(p.d*100)+'" data-thickness="'+i.id+'"></label><p class="small-help packed-readout">'+(i.kind==='bed'?'Includes mattress and dismantled frame.':'Tabletop stored upright with removed legs bundled behind it.')+' Packed: '+Math.round(p.w*100)+' × '+Math.round(p.d*100)+' × '+Math.round(p.h*100)+' cm. Confirm dismantling is possible; adjust bundle thickness.</p>':'')+(i.qty>1?'<p class="small-help">These dimensions apply to all '+i.qty+' of this item. Use a custom item for a different size.</p>':'');}
function add(id,qty=1){const i=bag.find(i=>i.id===id);if(bag.reduce((n,i)=>n+i.qty,0)+qty>150){$('status').textContent='For more than 150 items, please confirm a tailored layout with PurpleBox.';return false;}if(i)i.qty+=qty;else{const c=CATALOG.find(i=>i.id===id);if(c)bag.push({...c,qty});}return true;}
function eligible(){return units.filter(u=>u.eligible&&($('floor').value==='all'||u.floor===Number($('floor').value))).sort((a,b)=>a.area-b.area);}
function renderChoices(){const list=eligible();$('unitChoice').innerHTML=list.map(u=>'<option value="'+u.id+'"'+(selected?.id===u.id?' selected':'')+'>'+u.area.toFixed(1)+' sq ft · '+escape(u.label)+'</option>').join('');if(!bag.length||needsReview){$('recommendations').innerHTML='<p class="empty-options">'+(needsReview?'Review the unrecognised items above to get a complete recommendation.':'Add your items to discover your best fit.')+'</p>';return;}
 if(!recs.length){$('recommendations').innerHTML='<p class="empty-options">We couldn’t place every item in a single unit on the selected floors. Check dimensions or ask PurpleBox about combining units.</p>';return;}
 $('recommendations').innerHTML=recs.map((r,i)=>'<button class="recommendation '+(selected?.id===r.unit.id?'selected':'')+'" data-unit="'+r.unit.id+'" aria-pressed="'+(selected?.id===r.unit.id)+'"><span class="tag">'+(r.tight?'TIGHTER FIT':i===0?'BEST ESTIMATED FIT':'EXTRA ROOM')+'</span><strong>'+r.unit.area.toFixed(1)+' <small>sq ft</small></strong><span class="floor">'+escape(r.unit.label)+'</span><span class="fit">'+r.placedCount+' / '+r.count+' items placed</span></button>').join('');}
function updateView(animate=true){const count=bag.reduce((n,i)=>n+i.qty,0);$('saveImage').disabled=!bag.length||needsReview||!modelVisible||!webgl;$('obj').disabled=!bag.length||!webgl||needsReview||!renderer||!modelVisible;$('share').disabled=needsReview;
 if(selected&&bag.length){result=manualResult?.unit.id===selected.id?manualResult:packUnit(selected,bag,options());$('unitSize').innerHTML=selected.area.toFixed(1)+' <small>sq ft</small>';$('unitRef').textContent=selected.label+' · '+selected.w.toFixed(2)+' × '+selected.d.toFixed(2)+' m · '+(selected.height||2.4)+' m high';const recommended=!manualResult&&recs[0]?.unit.id===selected.id;$('viewBadge').textContent=needsReview?'ITEM LIST NEEDS REVIEW':recommended?'YOUR BEST ESTIMATED FIT':'TRYING ON A DIFFERENT SPACE';$('fitIcon').textContent=result.fit?'✓':'↗';$('fitCount').textContent=result.placedCount+' / '+count+' placed';$('fitText').textContent=needsReview?'Some written items still need review.':result.fit?'All selected items placed, including '+packingMetrics(result).stacked+' above-floor items.':result.unplaced.reduce((n,p)=>n+p.n,0)+' items still outside. Try a roomier unit.';showModel(result,animate);}else{result=null;$('unitSize').textContent='Let’s find your fit.';$('unitRef').textContent='Add your belongings to get started.';$('viewBadge').textContent='YOUR STORAGE SANDBOX';$('fitCount').textContent='';$('fitText').textContent='Your items will appear inside the suggested unit.';showModel(null,false);}
 if($('heightSummary')){const m=result?packingMetrics(result):null;$('heightSummary').textContent=m?'Height used: '+m.height.toFixed(2)+' / '+(selected.height||2.4).toFixed(2)+' m · Packed volume: '+m.volume.toFixed(1)+' / '+m.capacity.toFixed(1)+' m³ · '+m.stacked+' items above the floor. Packed volume accounts for items placed inside furniture spaces.':'';}renderPackingPlan();renderChoices();renderResult();syncFlow();if(result&&step===4)window.dispatchEvent(new CustomEvent('pb-unit',{detail:selected.id}));}
function renderPackingPlan(){const el=$('packingPlan');if(!el)return;if(!result){el.innerHTML='';return;}const plan=packingPlan(result),m=packingMetrics(result);el.innerHTML='<h3>How your items share the space</h3>'+(plan.length?'<p><strong>'+m.floorSaved.toFixed(1)+' m² of separate item footprints moved off the floor.</strong> These items share furniture space or a stack:</p><ul>'+plan.map(p=>'<li><strong>'+escape(p.base)+'</strong><span>'+Object.entries(p.items).map(([name,n])=>n+' × '+escape(name)).join(', ')+'</span></li>').join('')+'</ul>':'<p>No compatible mixed stacks were found for these dimensions and packing settings.</p>')+'<p class="small-help">Chair seats have a smaller usable area than the whole chair. A larger box stays elsewhere if it cannot fit. Review surface and contents settings under your item list.</p>';}
function refresh(auto=true,keepFields=false){manualResult=null;editMode=false;if($('manualMode'))$('manualMode').checked=false;if(controls)controls.enabled=true;if(!keepFields)renderBag();else $('volume').textContent=packedVolume(bag,$('stack').checked).toFixed(1)+' m³';renderCatalog();syncFlow();const n=++revision;
 if(step!==4)return;
 if(!bag.length||needsReview){go(2);return;}
 calculating=true;$('estimateBusy').hidden=false;$('resultContent').hidden=true;syncFlow();
 setTimeout(()=>{if(n!==revision)return;const found=recommend(units,bag,options());recs=found.choices;const list=eligible();if(auto||!selected||!list.some(u=>u.id===selected.id))selected=recs[0]?.unit||list[list.length-1];if(pendingPositions&&selected){let base=packUnit(selected,bag,options());const positions=pendingPositions;pendingPositions=null;let rebuilt={...base,placed:[],unplaced:[...base.placed,...base.unplaced],placedCount:0,fit:false};let valid=true;for(const p of positions){const t=movePack(rebuilt,p.k,p.x,p.z,p.r,options());if(!t.ok){valid=false;break;}rebuilt=t.result;}if(valid)manualResult=rebuilt;}calculating=false;$('estimateBusy').hidden=true;$('resultContent').hidden=false;updateView();},80);
}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function exportImage(){if(!result)return;const c=document.createElement('canvas');c.width=1400;c.height=Math.max(1050,810+Math.ceil(bag.length/2)*30);const x=c.getContext('2d');x.fillStyle='#f8f4fc';x.fillRect(0,0,c.width,c.height);x.fillStyle='#7236a4';x.font='bold 40px system-ui';x.fillText('purplebox',55,65);x.fillStyle='#473153';x.font='bold 32px system-ui';x.fillText('Your '+selected.area.toFixed(1)+' sq ft storage layout',55,120);x.font='18px system-ui';x.fillStyle='#90749e';x.fillText(selected.label+' · '+result.placedCount+' of '+result.count+' items placed · Estimated fit',55,159);
 if(webgl){for(const a of animations){a.g.position.y=a.base;a.g.scale.setScalar(1);}animations=[];renderer.render(scene,camera);x.fillStyle='#77569c';x.fillRect(45,185,1310,500);const image=renderer.domElement,ratio=Math.min(1310/image.width,500/image.height),w=image.width*ratio,h=image.height*ratio;x.drawImage(image,45+(1310-w)/2,185+(500-h)/2,w,h);}
 x.fillStyle='#644c76';x.font='18px system-ui';const rows=bag.map(i=>{const p=packedItem(i);return i.qty+' × '+i.name+' ('+Math.round(p.w*100)+' × '+Math.round(p.d*100)+' × '+Math.round(p.h*100)+' cm packed)';});for(let j=0;j<rows.length;j++)x.fillText(rows[j],55+(j%2)*650,730+Math.floor(j/2)*30,620);x.font='15px system-ui';x.fillStyle='#947fa0';x.fillText('Plan-based estimate. Confirm clear height, doors, safe stacking and availability with PurpleBox.',55,c.height-32);c.toBlob(b=>b&&download(b,'PurpleBox-my-storage-layout.png'));$('status').textContent='Your layout image is ready to send through WhatsApp.';}
function exportOBJ(){if(!webgl||!result)return;for(const a of animations){a.g.position.y=a.base;a.g.scale.setScalar(1);}animations=[];scene.updateMatrixWorld(true);let out='# PurpleBox illustrative layout; units in metres.\n',offset=1;modelRoot.traverse(o=>{if(!o.isMesh)return;const geo=o.geometry.index?o.geometry.toNonIndexed():o.geometry;const pos=geo.getAttribute('position'),v=new THREE.Vector3();out+='o part_'+offset+'\n';for(let i=0;i<pos.count;i++){v.fromBufferAttribute(pos,i).applyMatrix4(o.matrixWorld);out+='v '+v.x.toFixed(5)+' '+v.y.toFixed(5)+' '+v.z.toFixed(5)+'\n';}for(let i=0;i<pos.count;i+=3)out+='f '+[offset+i,offset+i+1,offset+i+2].join(' ')+'\n';offset+=pos.count;if(geo!==o.geometry)geo.dispose();});download(new Blob([out],{type:'text/plain'}),'PurpleBox-my-layout.obj');}
async function share(){if(!bag.length||needsReview||!result)return;const data={b:bag.map(i=>({id:i.id,qty:i.qty,w:i.w,d:i.d,h:i.h,packing:i.packing,packedDepth:i.packedDepth,nesting:i.nesting,nestRise:i.nestRise,supportTop:i.supportTop,loadClass:i.loadClass,allowTurn:i.allowTurn,luggagePosition:i.luggagePosition,...(i.id.startsWith('custom-')?{name:i.name}:{} )})),s:$('stack').checked,a:$('access').checked,f:$('floor').value,u:selected?.id,p:purpose,positions:manualResult?manualResult.placed.map(i=>({k:i.packKey,x:i.x,z:i.z,r:i.rot})):undefined};const url=new URL(location.href);url.search='';url.searchParams.set('layout',JSON.stringify(data));
 const text='My PurpleBox storage estimate: '+selected.area.toFixed(1)+' sq ft for '+result.count+' items. Estimated fit, subject to confirmation.';
 try{if(navigator.share){await navigator.share({title:'My PurpleBox Storage Estimate',text,url:url.href});$('status').textContent='Sharing menu closed.';}else{await navigator.clipboard.writeText(url.href);$('status').textContent='Estimate link copied. Paste it into your WhatsApp chat.';}}catch(e){if(e.name==='AbortError')return;try{await navigator.clipboard.writeText(url.href);$('status').textContent='Estimate link copied. Paste it into your WhatsApp chat.';}catch{history.replaceState(null,'',url.href);$('status').textContent='Copy the address from your browser to share your estimate.';}}
}
function restore(){try{const raw=new URLSearchParams(location.search).get('layout');if(!raw)return;const d=JSON.parse(raw);if(!Array.isArray(d.b))return;let total=0;for(const b of d.b.slice(0,150)){const c=CATALOG.find(c=>c.id===b.id);if(!c&&!/^custom-\d+$/.test(b.id))continue;const qty=Math.min(150,Math.max(0,Math.floor(Number(b.qty)||0)));if(total+qty>150)break;if([b.w,b.d,b.h].some(x=>!Number.isFinite(x)||x<.05||x>6))continue;if(!qty)continue;bag.push({...c,id:b.id,name:c?.name||String(b.name||'Custom item').slice(0,60),kind:c?.kind||'custom',color:c?.color||'#b592d0',w:b.w,d:b.d,h:b.h,nesting:b.nesting===true,nestRise:Number.isFinite(b.nestRise)&&b.nestRise>=.05&&b.nestRise<=b.h?b.nestRise:undefined,supportTop:typeof b.supportTop==='boolean'?b.supportTop:undefined,loadClass:['light','heavy','fragile'].includes(b.loadClass)?b.loadClass:undefined,allowTurn:typeof b.allowTurn==='boolean'?b.allowTurn:undefined,luggagePosition:b.luggagePosition==='upright'?'upright':undefined,packing:b.packing==='assembled'?'assembled':undefined,packedDepth:Number.isFinite(b.packedDepth)&&b.packedDepth>=.08&&b.packedDepth<=2?b.packedDepth:undefined,qty});total+=qty;}$('stack').checked=d.s!==false;$('access').checked=!!d.a;$('floor').value=['all','0','1','2'].includes(d.f)?d.f:'all';selected=units.find(u=>u.id===d.u&&u.eligible)||null;purpose=['home','business','mixed'].includes(d.p)?d.p:'mixed';if(Array.isArray(d.positions))pendingPositions=d.positions;}catch{$('status').textContent='This saved list could not be read. Start a new list below.';}}
function syncFlow(){document.querySelectorAll('[data-purpose]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.purpose===purpose)));const count=bag.reduce((n,i)=>n+i.qty,0);$('addedCount').textContent=count+' item'+(count===1?'':'s')+' added';$('stepLabel').textContent='Step '+(step-1)+' of 3';$('stepName').textContent=['Your storage','Your belongings','Review your list','Your unit'][step-1];
 document.querySelectorAll('.progress-track i').forEach((el,i)=>{el.className=i<step-2?'complete':i===step-2?'current':'';});
 $('back').hidden=step===2;$('next').innerHTML=[null,'Continue <span>→</span>','Review my '+count+' items <span>→</span>','Find my storage size <span>→</span>','Get a quote & reserve <span>→</span>'][step];
 $('next').disabled=!ready||calculating||(step===1&&!purpose)||(step===2&&(needsReview||!count))||(step===3&&(needsReview||!count));
 $('bottomHint').textContent=!ready?'Loading our unit sizes…':calculating?'Checking the sizes in our floor plans':step===1?(purpose?'You can change your answers as you go':'Choose an option to get started'):needsReview?'Review the unrecognised items before continuing':step===2?count+' items on your list':step===3?'You can adjust your estimate afterwards':'Your list stays with you when you make changes';
 $('reviewShortcut').disabled=!count||needsReview;$('share').disabled=!count||needsReview||calculating;
}
function go(n){if(n!==4){revision++;calculating=false;}step=n;document.querySelectorAll('.wizard-step').forEach(el=>el.hidden=Number(el.dataset.step)!==n);document.body.classList.toggle('result-mode',n===4);$('status').textContent='';syncFlow();window.scrollTo({top:0,behavior:'instant'});document.querySelector('[data-step="'+n+'"] h1')?.focus({preventScroll:true});
 if(n===2)setTimeout(makeThumbnails,30);if(n===4)refresh(false);window.dispatchEvent(new CustomEvent('pb-step',{detail:n}));
}
function renderResult(){if(step!==4||!result||!selected)return;const fit=result.fit;const best=recs[0]?.unit.id===selected.id;
 $('resultHeading').textContent=fit?'Here’s your estimated fit.':'Let’s adjust your estimate.';
 $('resultIntro').textContent=fit?'Based on your '+result.count+' items and the packing options you chose.':'This unit could not accommodate your full list. Try a larger option or revise your items.';
 $('resultTag').textContent=manualResult?'YOUR CUSTOM ARRANGEMENT':fit?(best?'RECOMMENDED SIZE':'YOUR SELECTED SIZE'):'NOT A COMPLETE FIT';
 $('recommendedArea').innerHTML=selected.area.toFixed(1)+' <small>sq ft</small>';
 $('recommendedRef').textContent=selected.label+' · '+selected.w.toFixed(2)+' × '+selected.d.toFixed(2)+' m · '+(selected.height||2.4)+' m high';
 $('resultItems').textContent=result.placedCount+' of '+result.count+' items placed';$('resultVolume').textContent=packedVolume(bag,$('stack').checked).toFixed(1)+' m³ of belongings';
 $('resultReason').textContent=manualResult?'Your arrangement has been checked for overlap, unit boundaries and the selected aisle.':fit?(best?'Our packing check aims to leave at least 10% extra floor area around the packed footprints where a suitable unit exists. Check access and final fit with our team.':'A different size to compare with your recommended option.'):(recs.length?'Some items remain outside. Open the comparison below to choose a unit that fits.':'No single plan unit fits the complete list in this check. PurpleBox can help with a combination of units.');
 $('reveal3D').hidden=modelVisible;$('modelSection').hidden=!modelVisible;
}
function revealModel(){modelVisible=true;$('modelSection').hidden=false;$('reveal3D').hidden=true;if(!renderer&&webgl)init3D();resize();showModel(result,true);$('saveImage').disabled=!webgl||needsReview;$('obj').disabled=!webgl||needsReview;installEditor();setTimeout(()=>$('modelSection').scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'}),60);}
function wireJourney(){
 $('back').onclick=()=>go(Math.max(2,step-1));$('next').onclick=()=>{if(step===1){go(2);return;}if(step===2){if(!bag.length||needsReview){syncFlow();return;}go(3);return;}if(step===3){const invalid=$('bagItems').querySelector('input:invalid');if(invalid){invalid.reportValidity();return;}selected=null;go(4);return;}if(step===4){goToReserve();return;}go(3);};
 $('reviewShortcut').onclick=()=>{if(bag.length&&!needsReview)go(3);};
 $('addFromReview').onclick=()=>{go(2);};$('editResult').onclick=()=>go(3);$('reveal3D').onclick=revealModel;$('addResult').onclick=()=>go(2);
 $('quoteStart').onclick=goToReserve;
}
const RESERVE_PLANS=[[10,'XS',330],[25,'SS',650],[35,'M',775],[50,'S',950],[75,'M+',1300],[100,'L',1600],[150,'XL',2500],[200,'XXL',3000]];
function nearestReservePlan(sqft){for(const p of RESERVE_PLANS){if(sqft<=p[0])return p;}return RESERVE_PLANS[RESERVE_PLANS.length-1];}
function goToReserve(){const plan=nearestReservePlan(selected?selected.area:0);const params=new URLSearchParams();params.set('unitLabel',plan[1]);params.set('unitSize',plan[0]+' sq ft ('+plan[1]+')');params.set('monthlyRent',String(plan[2]));const qs=params.toString();let embedded=false;try{embedded=window.top&&window.top!==window&&!!window.top.location.href;}catch(e){embedded=false;}if(embedded){const abs=new URL('reserve-step-1.html',window.top.location.href);abs.search=qs;window.top.location.href=abs.href;}else{location.href='../reserve-step-1.html?'+qs;}}
let editorInstalled=false,dragState=null;
function renderEditor(){if(!$('packSelect')||!result)return;const all=[...result.placed,...result.unplaced];if(!all.some(p=>p.packKey===selectedPack))selectedPack=all[0]?.packKey||null;$('packSelect').innerHTML=all.map(p=>'<option value="'+p.packKey+'" '+(p.packKey===selectedPack?'selected':'')+'>'+escape(p.name)+(p.n>1?' × '+p.n+' (stack)':'')+(result.unplaced.some(x=>x.packKey===p.packKey)?' · outside unit':'')+'</option>').join('');for(const id of ['packSelect','moveLeft','moveRight','moveBack','moveForward','rotateItem'])$(id).disabled=!editMode;if(controls)controls.enabled=!editMode;}
function chosenPack(){return [...(result?.placed||[]),...(result?.unplaced||[])].find(p=>p.packKey===selectedPack);}
function clearGhost(){if(dragGhost){scene.remove(dragGhost);dragGhost.geometry.dispose();dragGhost.material.dispose();dragGhost=null;}}
function commitMove(t){if(!t.ok){$('moveStatus').textContent=t.reason;return;}manualResult=t.result;result=t.result;clearGhost();updateView(false);$('moveStatus').textContent='Position saved. '+result.placedCount+' of '+result.count+' items placed.';}
function nudge(dx,dz,rotate=false){const p=chosenPack();if(!editMode||!p)return;const rot=rotate?!p.rot:!!p.rot;const x=p.x??.04,z=p.z??.04;commitMove(movePack(result,p.packKey,Math.round((x+dx)*1000)/1000,Math.round((z+dz)*1000)/1000,rot,options()));}
function installEditor(){if(editorInstalled||!renderer||!webgl)return;editorInstalled=true;
 $('manualMode').onchange=e=>{editMode=e.target.checked;controls.autoRotate=false;$('rotate').setAttribute('aria-pressed','false');if(animations.length){for(const a of animations){a.g.position.y=a.base;a.g.scale.setScalar(1);}animations=[];}clearGhost();renderEditor();$('moveStatus').textContent=editMode?'Drag an item, or select one and tap an empty floor position. Arrows move it 10 cm.':'Camera controls are active. Your arrangement is kept.';};
 $('packSelect').onchange=e=>{selectedPack=e.target.value;$('moveStatus').textContent='Selected '+chosenPack().name+'. Drag or use the arrows.';};
 $('moveLeft').onclick=()=>nudge(-.1,0);$('moveRight').onclick=()=>nudge(.1,0);$('moveBack').onclick=()=>nudge(0,-.1);$('moveForward').onclick=()=>nudge(0,.1);$('rotateItem').onclick=()=>nudge(0,0,true);
 $('autoPack').onclick=()=>{manualResult=null;editMode=false;$('manualMode').checked=false;clearGhost();updateView();$('moveStatus').textContent='Automatic packing restored for this unit.';};
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),plane=new THREE.Plane(new THREE.Vector3(0,1,0),0);
 const floorPoint=e=>{const r=$('scene').getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);return ray.ray.intersectPlane(plane,new THREE.Vector3());};
 const start=e=>{if(!editMode||!result)return;e.preventDefault();e.stopImmediatePropagation();const pt=floorPoint(e);if(!pt)return;const hit=ray.intersectObjects(hoverTargets,true)[0];if(hit){let o=hit.object;while(o&&!o.userData.packKey)o=o.parent;if(o)selectedPack=o.userData.packKey;}$('packSelect').value=selectedPack;const p=chosenPack();if(!p)return;dragState={id:e.pointerId,rot:!!p.rot};$('scene').setPointerCapture(e.pointerId);preview(e);};
 const preview=e=>{if(!dragState)return;e.preventDefault();e.stopImmediatePropagation();const pt=floorPoint(e),p=chosenPack();if(!pt||!p)return;const pw=p.rot?p.d:p.w,pd=p.rot?p.w:p.d,x=Math.round((pt.x+result.unit.w/2-pw/2)*20)/20,z=Math.round((pt.z+result.unit.d/2-pd/2)*20)/20;const t=movePack(result,p.packKey,x,z,!!p.rot,options());dragState.trial=t;clearGhost();dragGhost=new THREE.Mesh(new THREE.BoxGeometry(pw,p.ph,pd),new THREE.MeshBasicMaterial({color:t.ok?'#b7e18b':'#efb37c',transparent:true,opacity:.38,depthWrite:false}));dragGhost.position.set(x+pw/2-result.unit.w/2,p.ph/2,z+pd/2-result.unit.d/2);scene.add(dragGhost);$('moveStatus').textContent=t.ok?'Release to place here.':t.reason;};
 $('scene').addEventListener('pointerdown',start,true);$('scene').addEventListener('pointermove',preview,true);$('scene').addEventListener('pointerup',e=>{if(!dragState)return;e.preventDefault();e.stopImmediatePropagation();const t=dragState.trial;dragState=null;clearGhost();if(t)commitMove(t);},true);$('scene').addEventListener('pointercancel',()=>{dragState=null;clearGhost();},true);
 $('scene').addEventListener('keydown',e=>{if(!editMode)return;const keys={ArrowLeft:[-.1,0],ArrowRight:[.1,0],ArrowUp:[0,-.1],ArrowDown:[0,.1]};if(keys[e.key]){e.preventDefault();e.stopImmediatePropagation();nudge(...keys[e.key]);}},true);renderEditor();
}

function wire(){
 wireJourney();
 $('catalog').onclick=e=>{const plus=e.target.closest('[data-add]'),minus=e.target.closest('[data-minus]');if(plus){const id=plus.dataset.add,existing=bag.find(i=>i.id===id);if(add(id)&&!existing&&catalogueSizes.has(id))Object.assign(bag.find(i=>i.id===id),catalogueSizes.get(id));refresh();$('selectionFeedback').textContent='Item added to your selected list.';}if(minus){const i=bag.find(i=>i.id===minus.dataset.minus);if(i)i.qty--;bag=bag.filter(i=>i.qty>0);refresh();}};
 $('catalog').onchange=e=>{const id=e.target.dataset.catalogSize;if(!id||e.target.value==='')return;const base=CATALOG.find(i=>i.id===id),p=itemSizes(base)[Number(e.target.value)],dims={w:p.w,d:p.d,h:p.h};catalogueSizes.set(id,dims);const selected=bag.find(i=>i.id===id);if(selected)Object.assign(selected,dims);refresh();$('selectionFeedback').textContent=p.label+' size selected for '+base.name+(selected?' · applies to all '+selected.qty:'')+'.';};$('search').oninput=renderCatalog;
 $('bagItems').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.remove){bag=bag.filter(i=>i.id!==b.dataset.remove);refresh();$('listFeedback').textContent='Item removed.';}else if(b.dataset.delta){const item=bag.find(i=>i.id===b.dataset.id);if(Number(b.dataset.delta)>0){add(item.id);}else item.qty--;bag=bag.filter(i=>i.qty>0);refresh();}};
 $('bagItems').onchange=e=>{const t=e.target;if(t.dataset.turn){bag.find(i=>i.id===t.dataset.turn).allowTurn=t.checked;refresh();return;}if(t.dataset.load||t.dataset.luggage){const i=bag.find(i=>i.id===(t.dataset.load||t.dataset.luggage));if(t.dataset.load)i.loadClass=t.value;else i.luggagePosition=t.value;refresh();return;}if(t.dataset.nesting||t.dataset.support||t.dataset.rise){const i=bag.find(i=>i.id===(t.dataset.nesting||t.dataset.support||t.dataset.rise));if(t.dataset.rise){const v=Number(t.value);if(!Number.isFinite(v)||v<5||v>i.h*100){t.setCustomValidity('Enter 5 cm up to the chair height.');t.reportValidity();return;}i.nestRise=v/100;}else if(t.dataset.nesting)i.nesting=t.checked;else i.supportTop=t.checked;refresh();return;}if(t.dataset.size){if(t.value==='')return;const i=bag.find(i=>i.id===t.dataset.size);if(!CATALOG.some(c=>c.id===i.id)&&!i.sizeBase)i.sizeBase={w:i.w,d:i.d,h:i.h};const p=itemSizes(i)[Number(t.value)];Object.assign(i,{w:p.w,d:p.d,h:p.h});refresh();return;}if(t.dataset.packing){bag.find(i=>i.id===t.dataset.packing).packing=t.value==='assembled'?'assembled':undefined;refresh();return;}if(t.dataset.thickness){const v=Number(t.value);if(v<8||v>200||!Number.isFinite(v)){t.setCustomValidity('Use 8–200 cm.');t.reportValidity();return;}bag.find(i=>i.id===t.dataset.thickness).packedDepth=v/100;t.setCustomValidity('');refresh(true,true);updatePackedReadout(t);return;}if(!e.target.dataset.dim)return;const val=Number(e.target.value);if(!Number.isFinite(val)||val<5||val>600){e.target.setCustomValidity('Use 5 to 600 cm.');e.target.reportValidity();return;}e.target.setCustomValidity('');const i=bag.find(i=>i.id===e.target.dataset.id);i[e.target.dataset.dim]=val/100;if(i.shape==='round'&&e.target.dataset.dim==='w')i.d=i.w;refresh(true,true);updatePackedReadout(t);};
 $('clear').onclick=()=>{bag=[];needsReview=false;refresh();go(2);};
 $('roomChoice').innerHTML=ROOM_CATEGORIES.map(r=>'<option value="'+r.id+'">'+r.name+'</option>').join('');$('roomChoice').value=category;$('roomChoice').onchange=e=>{category=e.target.value;$('search').value='';renderCatalog();};
 $('recommendations').onclick=e=>{const b=e.target.closest('[data-unit]');if(b){revision++;selected=units.find(u=>u.id===b.dataset.unit);updateView();}};$('unitChoice').onchange=e=>{revision++;selected=units.find(u=>u.id===e.target.value);updateView();};for(const id of ['floor','stack','access'])$(id).onchange=()=>refresh();
 $('replay').onclick=()=>showModel(result);$('resetView').onclick=()=>positionCamera(selected||{w:3,d:3},true);$('rotate').onclick=()=>{if(!webgl)return;controls.autoRotate=!controls.autoRotate;$('rotate').setAttribute('aria-pressed',String(controls.autoRotate));};$('topView').onclick=()=>{if(!webgl)return;top=!top;if(top){const span=Math.max(selected?.w||3,selected?.d||3);camera.position.set(0,span*2.2,.001);controls.target.set(0,0,0);controls.update();$('topView').textContent='3D view';}else positionCamera(selected||{w:3,d:3},true);};$('zoomIn').onclick=()=>zoom(.85);$('zoomOut').onclick=()=>zoom(1.15);$('saveImage').onclick=exportImage;$('obj').onclick=exportOBJ;$('share').onclick=share;
 $('customOpen').onclick=()=>$('customDialog').showModal();$('closeCustom').onclick=()=>$('customDialog').close();$('customForm').onsubmit=e=>{e.preventDefault();if(bag.reduce((n,i)=>n+i.qty,0)>=150){$('status').textContent='The playground supports up to 150 items.';return;}bag.push({id:'custom-'+Date.now(),name:$('customName').value.trim()||'Custom item',w:Number($('customW').value)/100,d:Number($('customD').value)/100,h:Number($('customH').value)/100,kind:'custom',color:'#b592d0',qty:1});$('customDialog').close();refresh();};
 $('viewData').onclick=()=>{$('dataBody').innerHTML=units.map(u=>'<tr class="'+(u.eligible?'':'needs-check')+'"><td>'+escape(u.label)+'</td><td>'+u.area.toFixed(1)+'</td><td>'+u.w.toFixed(2)+' × '+u.d.toFixed(2)+'</td><td>'+escape(u.eligible?'Included · '+u.dimensionSource:u.note)+'</td></tr>').join('');$('dataDialog').showModal();};$('closeData').onclick=()=>$('dataDialog').close();
}
async function init(){wire();renderCatalog();renderBag();syncFlow();try{const r=await fetch(new URL('./units.json',import.meta.url));if(!r.ok)throw Error();units=await r.json();restore();ready=true;if(bag.length){go(4);}else go(2);}catch{$('status').textContent='The unit sizes could not load. Please refresh this page to try again.';$('bottomHint').textContent='Unit sizes unavailable — refresh to retry';}}
window.pb={go,get step(){return step;},snapshot:()=>({items:bag.map(i=>({...i})),unit:selected?.id,area:selected?.area,purpose,options:options(),positions:manualResult?manualResult.placed.map(p=>({k:p.packKey,x:p.x,z:p.z,r:p.rot})):undefined})};
init();
