// Categories only filter the catalogue; they never add items or replace a list.
export const ROOM_CATEGORIES=[
 {id:'bedroom',name:'Bedroom',description:'Beds, mattresses, drawers, wardrobes, lighting, rugs, TVs and bedroom belongings',cats:['Bedroom'],ids:['armchair','ottoman','chair','bookcase','mirror','rug','lamp','art','tv','console','desk','officechair','smallbox','box','largebox','wardrobebox','plasticbin','duvetbag','suitcase','ac','monitor']},
 {id:'living',name:'Living room',description:'Sofas, coffee tables, media furniture, lighting and decor',cats:['Living'],exclude:['table','chair','dining-small','dining-large','dining-round-small','dining-round-large','dining-two','bike'],ids:['lamp','rug','art','mirror','smallbox','box','largebox','plasticbin','ac']},
 {id:'dining',name:'Dining room',description:'Round and rectangular dining tables, chairs, sideboards and decor',ids:['dining-two','dining-small','table','dining-large','dining-round-small','dining-round-large','chair','sideboard','console','display','lamp','mirror','art','rug','smallbox','box','largebox']},
 {id:'kitchen',name:'Kitchen & utility',description:'Appliances, storage furniture, boxes and household equipment',cats:['Appliances'],ids:['rack','bookcase','smallbox','box','largebox','plasticbin','dining-two','chair']},
 {id:'boxes',name:'Boxes & luggage',description:'Choose each box size and quantity, plus suitcases, bags and storage bins',cats:['Boxes'],ids:['archive','stockbox','flightcase'],order:['smallbox','box','largebox','bookbox','archive','stockbox','wardrobebox','plasticbin','suitcase','duvetbag','sportsbag','flightcase']},
 {id:'garden',name:'Garden, garage & fitness',description:'Outdoor furniture, bicycles, tools and fitness equipment',cats:['Villa & garden'],ids:['bike','rack','commercialshelf','plasticbin','smallbox','box','largebox','flightcase']},
 {id:'office',name:'Office & study',description:'Desks, office chairs, filing, shelving, equipment and office decor',cats:['Office'],ids:['desk','officechair','filing','rack','archive','bookbox','bookcase','lamp','rug','art','tv','smallbox','box','largebox','plasticbin']},
 {id:'business',name:'Business stock & equipment',description:'Retail displays, stock cartons, pallets, archive storage and business equipment',cats:['Business','Retail & stock'],ids:['smallbox','box','largebox','plasticbin','bookbox','printer','copier','server','officecupboard']},
 {id:'all',name:'All items',description:'Browse every household and business item'}
];
export function itemsForRoom(catalog,id){const room=ROOM_CATEGORIES.find(r=>r.id===id)||ROOM_CATEGORIES[0];const items=catalog.filter(i=>room.id==='all'||(!(room.exclude||[]).includes(i.id)&&((room.cats||[]).includes(i.cat)||(room.ids||[]).includes(i.id))));if(room.order)items.sort((a,b)=>{const rank=i=>{const n=room.order.indexOf(i.id);return n<0?999:n;};return rank(a)-rank(b);});return items;}
