import defaults from './defaults.js';
import {calculate,unitOffer,scoreLead,validateConfig} from './commerce.js';
import {CATALOG,packUnit,movePack} from './engine.js';
import assets from './assets.js';
const json=(v,status=200)=>new Response(JSON.stringify(v),{status,headers:{'content-type':'application/json','cache-control':'no-store','x-content-type-options':'nosniff'}});
const db=env=>{if(!env.DB)throw Error('Database unavailable');return env.DB;};
const admin=(req,env)=> (env.ADMIN_EMAILS||'').toLowerCase().split(',').includes((req.headers.get('oai-authenticated-user-email')||'!').toLowerCase());
async function config(env){const row=await db(env).prepare('SELECT value,revision FROM settings WHERE id=?').bind('main').first();return row?{...JSON.parse(row.value),revision:row.revision}:structuredClone(defaults);}
async function body(req){if(Number(req.headers.get('content-length'))>100000)throw Error('Request too large');const s=await req.text();if(s.length>100000)throw Error('Request too large');return JSON.parse(s);}
function inventory(data){if(!Array.isArray(data.items)||!data.items.length||data.items.length>150)throw Error('Choose your items first.');let count=0;const ids=new Set();return data.items.map(i=>{const base=CATALOG.find(c=>c.id===i.id);if(!base&&!/^custom-\d+$/.test(i.id))throw Error('Unknown item');if(ids.has(i.id))throw Error('Duplicate item');ids.add(i.id);if(!Number.isInteger(i.qty)||i.qty<1||(count+=i.qty)>150||[i.w,i.d,i.h].some(n=>typeof n!=='number'||!Number.isFinite(n)||n<.05||n>6))throw Error('Check item quantities and dimensions.');if(i.packedDepth!==undefined&&(!Number.isFinite(i.packedDepth)||i.packedDepth<.08||i.packedDepth>2))throw Error('Check packed thickness.');return {...base,id:i.id,name:base?.name||String(i.name||'Custom item').slice(0,60),kind:base?.kind||'custom',w:i.w,d:base?.shape==='round'?i.w:i.d,h:i.h,qty:i.qty,packing:i.packing==='assembled'?'assembled':undefined,packedDepth:i.packedDepth,nesting:i.nesting===true,supportTop:typeof i.supportTop==='boolean'?i.supportTop:undefined,loadClass:['light','heavy','fragile'].includes(i.loadClass)?i.loadClass:undefined,allowTurn:typeof i.allowTurn==='boolean'?i.allowTurn:undefined,luggagePosition:i.luggagePosition==='upright'?'upright':undefined,nestRise:Number.isFinite(i.nestRise)&&i.nestRise>=.05&&i.nestRise<=i.h?i.nestRise:undefined};});}
function getEstimate(data,c){const items=inventory(data),units=JSON.parse(assets['/units.json'].body),unit=units.find(u=>u.id===data.unit&&u.eligible);if(!unit)throw Error('Choose a valid unit.');const options={stack:data.options?.stack!==false,access:!!data.options?.access};let result=packUnit(unit,items,options);if(Array.isArray(data.positions)&&data.positions.length<=150){let rebuilt={...result,placed:[],unplaced:[...result.placed,...result.unplaced],placedCount:0,fit:false};for(const p of data.positions){const moved=movePack(rebuilt,p.k,p.x,p.z,!!p.r,options);if(!moved.ok)throw Error('Your saved layout needs to be checked again.');rebuilt=moved.result;}result=rebuilt;}const services={moving:!!data.services?.moving,packing:!!data.services?.packing,padlock:!!data.services?.padlock};const quote=calculate(c,unit.area,data.weeks===null?null:Number(data.weeks),services);return {items,unit:unit.id,area:unit.area,unitLabel:unit.label,positions:data.positions,options,services,quote:result.fit?quote:{manual:true,reason:'Our team needs to review the fit of this inventory.',revision:c.revision},fit:result.fit};}
export default {async fetch(req,env){try{const url=new URL(req.url),path=url.pathname;const isAdmin=admin(req,env);
 if(req.method!=='GET'&&req.headers.get('origin')&&req.headers.get('origin')!==url.origin)return json({error:'Origin not allowed'},403);
 if(path.startsWith('/api/admin/')&&!isAdmin)return json({error:'Staff sign-in required'},403);
 if(path==='/admin'&&!isAdmin)return new Response('<p>Staff access only. <a target="_top" href="/signin-with-chatgpt?return_to=/admin">Sign in</a></p>',{status:403,headers:{'content-type':'text/html'}});
 if(path==='/api/config'&&req.method==='GET'){const c=await config(env);return json({revision:c.revision,location:c.location,vat:c.vat,access:c.access,maps:c.maps,tour:c.tour,photos:c.photos,whatsapp:c.whatsapp});}
 if(path==='/api/offer'&&req.method==='POST'){const c=await config(env),d=await body(req),estimate=getEstimate({...d,weeks:2},c),o=unitOffer(c,estimate.area);return json(o?{size:o.size,parts:o.parts.map(p=>({size:p.size,qty:p.qty})),combined:o.combined,fit:estimate.fit}:{manual:true});}
 if(path==='/api/quote'&&req.method==='POST'){const c=await config(env),data=await body(req);return json(getEstimate(data,c));}
 if(path==='/api/request'&&req.method==='POST'){const d=await body(req);if(!/^[a-f0-9-]{36}$/.test(d.id)||typeof d.name!=='string'||!d.name.trim()||d.name.length>80||(typeof d.phone!=='string'||!/^\+?[\d ()-]{8,25}$/.test(d.phone)||!/^\d{8,15}$/.test(d.phone.replace(/\D/g,'')))||!d.consent||!['reserve','visit','quote'].includes(d.action)||!['today','3days','7days','14days','30days','90days','later','research'].includes(d.timing))return json({error:'Check your name, WhatsApp number and request details.'},400);
 const c=await config(env);if(d.revision!==c.revision)return json({error:'Prices have changed. Refresh your quotation before submitting.'},409);
 const existing=await db(env).prepare('SELECT id FROM leads WHERE id=?').bind(d.id).first();if(existing)return json({id:existing.id,saved:true});
 const estimate=getEstimate(d,c),data={...estimate,name:d.name.trim(),phone:d.phone,purpose:['home','business','mixed'].includes(d.purpose)?d.purpose:'mixed',timing:d.timing,start:String(d.start||'').slice(0,10),weeks:d.weeks,durationChoice:String(d.durationChoice||'').slice(0,20),action:d.action,source:String(d.source||'Direct').slice(0,160),consent:true,followupConsent:!!d.followupConsent,created:new Date().toISOString()};data.qualification=scoreLead(data,c);
 await db(env).prepare('INSERT INTO leads (id,created,status,score,data) VALUES (?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(d.id,data.created,'New',data.qualification.score,JSON.stringify(data)).run();return json({id:d.id,saved:true},201);}
 if(path==='/api/event'&&req.method==='POST'){const d=await body(req);if(!['started','inventory_completed','recommended','quote_viewed','availability_checked','request_saved','tour_opened'].includes(d.kind)||typeof d.session!=='string'||d.session.length>60)return json({error:'Invalid event'},400);await db(env).prepare('INSERT INTO events (id,session,kind,created,source) VALUES (?,?,?,?,?)').bind(crypto.randomUUID(),d.session,d.kind,new Date().toISOString(),String(d.source||'Direct').slice(0,160)).run();return json({ok:true});}
 if(path==='/api/admin/config'&&req.method==='GET')return json(await config(env));
 if(path==='/api/admin/config'&&req.method==='PUT'){const c=validateConfig(await body(req));const old=await config(env);if(c.revision!==old.revision)return json({error:'Another staff member changed this configuration. Reload before saving.'},409);const saved=await db(env).prepare('INSERT INTO settings (id,value,revision) VALUES (?,?,1) ON CONFLICT(id) DO UPDATE SET value=excluded.value,revision=settings.revision+1 WHERE settings.revision=?').bind('main',JSON.stringify(c),c.revision).run();if(!saved.meta.changes)return json({error:'Configuration changed. Reload.'},409);return json(await config(env));}
 if(path==='/api/admin/leads'&&req.method==='GET'){const rows=await db(env).prepare('SELECT * FROM leads ORDER BY score DESC,created DESC LIMIT 500').all();return json(rows.results.map(r=>({...r,data:JSON.parse(r.data)})));}
 if(path==='/api/admin/lead'&&req.method==='PUT'){const d=await body(req);if(!['New','Contacted','Quoted','Visit planned','Reserved','Won','Lost','Nurture'].includes(d.status))throw Error('Invalid status');await db(env).prepare('UPDATE leads SET status=?,assigned=?,followup=? WHERE id=?').bind(d.status,String(d.assigned||'').slice(0,80),String(d.followup||'').slice(0,10),d.id).run();return json({ok:true});}
 if(path==='/api/admin/funnel'&&req.method==='GET'){const rows=await db(env).prepare('SELECT kind,COUNT(DISTINCT session) AS sessions FROM events GROUP BY kind').all();return json(rows.results);}
 if(path.startsWith('/api/'))return json({error:'Not found'},404);
 if(!['GET','HEAD'].includes(req.method))return new Response('Method not allowed',{status:405});const a=assets[path==='/'?'/index.html':path==='/admin'?'/admin.html':path];if(!a)return new Response('Not found',{status:404});return new Response(req.method==='HEAD'?null:a.body,{headers:{'content-type':a.type,'cache-control':'no-cache','x-content-type-options':'nosniff','referrer-policy':'strict-origin-when-cross-origin'}});
 }catch(e){console.error('Request failed',e.message);return json({error:e.message==='Database unavailable'?'Temporarily unavailable. Your list is still here; please try again.':String(e.message).slice(0,180)},400);}}};
